#!/bin/bash

DSKSRV_ROOT_DIR=$TOOLS_ROOT_DIR/os8-disk-server
DSKSRV_DIR=$DSKSRV_ROOT_DIR/os8diskserver
DSKSRV_DISKS_DIR=$DSKSRV_ROOT_DIR/disks
DSKSRV_SIMH_ENV_DIR=$DSKSRV_ROOT_DIR/diskserver-env/simh
DSKSRV_PDP12_ENV_DIR=$DSKSRV_ROOT_DIR/diskserver-env/pdp12

RES_ROOT_DIR=$TOOLS_ROOT_DIR/resources
RES_UNMODIF_DISKS_DIR=$RES_ROOT_DIR/unmodified-umd-disks
RES_MINICOM_DATA_DIR=$RES_ROOT_DIR/minicom-data

SIMH_DIR=$TOOLS_ROOT_DIR/simh

SCRIPTS_DIR=$TOOLS_ROOT_DIR/scripts

MINICOM_DIR=$TOOLS_ROOT_DIR/minicom

CONFIG_DIR=$TOOLS_ROOT_DIR/config

LEGACY_DISKS_DIR=$TOOLS_ROOT_DIR/disks
